### ISSUE TITLE
Pull configuration from a blobstore

### ISSUE THREAD

**Issue by wendorf** [zlabjp/kubernetes-resource#16]
I'm currently building a pipeline that first creates a cluster, then performs operations on it. Because of that, the kubeconfig is not available at `set-pipeline`-time. I would like to be able to specify a remote location for the kubeconfig, similar to how the [terraform-resource](https://github.com/ljfranklin/terraform-resource) supports `storage.*` configuration.

My personal use-case is to pull from S3.

**Comment by superbrothers** [comment]
I'll check the terraform-resource's behavior. Thanks.

**Comment by superbrothers** [comment]
I don't implement storage drivers into the kubernetes-resource, because to do that is not flexible and I wouldn't like to maintain storage drivers.
So we will add the `kubeconfig_file` param into the output params of this resource. This param is a kubeconfig file that you can use any file as it. It allows you to use an any remote kubeconfig file fetched by another resources such as s3-resource. The below is an example pipeline.

```yaml
resources:
- name: k8s-prod
  type: kubernetes

- name: kubeconfig
  type: s3
  source:
    bucket: mybucket
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret))

- name: my-app
  type: git
  source:
    ...

jobs:
- name: k8s-deploy-prod
  plan:
  - aggregate:
    - get: my-app
      trigger: true
    - get: remote-kubeconfig
  - put: k8s-prod
    params:
      kubectl: apply -f my-app/k8s -f my-app/k8s/production
      wait_until_ready_selector: app=myapp
      kubeconfig_file: kubeconfig/file
```

@wendorf What do you think about this change?
