### ISSUE TITLE
Does not work with GCP Kubernetes clusters

### ISSUE THREAD

**Issue by jacob-hd** [zlabjp/kubernetes-resource#25]
Following your advice from #17, I set up a `bot` serviceaccount and rolebinding like so:
```
kubectl create serviceaccount --namespace kube-system bot
kubectl create rolebinding bot-cluster-role --clusterrole=cluster-admin --serviceaccount=kube-system:bot
```

Next, I used `kubernetes-scripts` to generate a kubeconfig and save it to a Kubernetes secret:
```
git clone https://github.com/zlabjp/kubernetes-scripts.git
cd kubernetes-scripts
./create-kubeconfig bot --namespace kube-system > kubeconfig.yaml
kubectl create secret generic kubeconfig-bot --namespace concourse-main --from-file=value=kubeconfig.yaml
```

All gravy.

I set up the resource:
```
resources:
- name: kubernetes-secret
  type: kubernetes
  source:
    kubeconfig: ((kubeconfig-bot))

jobs:
- name: refresh-github-auth-every-55m
  ...
  - put: kubernetes-secret
    params:
      kubectl: get services
```

The kubeconfig must be working, because the output shows that we're connected to the cluster:
![image](https://user-images.githubusercontent.com/31864739/39443939-dfeca916-4c6a-11e8-9d57-294361119d8f.png)

The `kubectl version` and `kubectl cluster-info` appear to work, as if the authorization of the `bot` user worked. But no other `kubectl` commands, like `kubectl get services` work. Therefore, I am not able to apply the secret that I wish to apply in this pipeline.

The insidious error:
```
User "system:serviceaccount:kube-system:bot" cannot list nodes at the cluster scope: Unknown user "system:serviceaccount:kube-system:bot"
```

I have tried every possible combination of roles and role bindings, so this doesn't appear to be related to RBAC at all. But I'm not sure...

Any help is greatly appreciated!

**Comment by jacob-hd** [comment]
After much trial and error, I realized that following the instructions here for enabling legacy authorization was not sufficient:
https://cloud.google.com/kubernetes-engine/docs/how-to/iam-integration

You also have to go to the GCP admin panel for the cluster, click "Edit", and then change this value as well:
![image](https://user-images.githubusercontent.com/31864739/39446511-9cf48328-4c73-11e8-8247-13764824dce0.png)

After that, all was well!

Thanks for the excellent resource. :smile:

**Comment by superbrothers** [comment]
@jacob-hd I'll add more information to README about using this resource on GKE. Thank you for letting me know! 😄

**Comment by larssb** [comment]
@jacob-hd why do you create a secret on the GCP Kubernetes engine when you are using the kube-config you generated via the create-kubeconfig script?

Like in your pipeline def.
```yaml
resources:
- name: kubernetes-secret
  type: kubernetes
  source:
    kubeconfig: ((kubeconfig-bot))
```

I'm curious because I would like to be able to use a "secret" set on GCP Kubernetes. Have you been able to do that @jacob-hd ???? Others are welcome to chirp in as well.

Thank you very much.
