### ISSUE TITLE
How to pass the build versions dynamically in kubectl command 

### ISSUE THREAD

**Issue by sanjay2916** [zlabjp/kubernetes-resource#33]
Hi,

I am pushing the docker images to ECR with version number which is stored in S3 and i am not able to use those version number in kubectl command dynamically

eg:

- put: k8s
      params:
        kubectl: set image deployment/nginx0-deployment nginx=1.amazonaws.com/test
        tag: version/number
        wait_until_ready: 300

tag: version/number :  this value not taking in kubectl argument dynamically

**Comment by dober** [comment]
Same question with shared output tag file

**Comment by lnhrdt** [comment]
While it might be nice to feed version numbers into a k8s configuration by using this resource's api, I find I also want to template many other values in my k8s configurations so it's easy enough to handle them all in a task prior to calling this resource. You'd need to create configuration files for pods/deployments/etc instead of calling `kubectl set image ...` like you're doing, but you know using a declarative approach to describing your infrastructure is probably a good idea anyway 😉

Here's an example from a project of mine that I've been satisfied with, in case you'd like to borrow pieces:

**example k8s config**

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: ${DOCKER_REGISTRY}/${DOCKER_ORGANIZATION}/web:${VERSION}
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: ${HOST}
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http
```

**example Concourse task to populate values:**

```yaml
  - task: generate k8s configuration
    file: pipeline-tasks-source/pipeline/tasks/k8s/configure-deployment-with-version.yml
    input_mapping: {source: web-k8s-configuration-source, version: web-version}
    output_mapping: {configuration: web-k8s-configuration}
    params:
      FILE: web.yml
      DOCKER_REGISTRY: ((docker.registry))
      DOCKER_ORGANIZATION: ((docker.organization))
      HOST: ((environment.development.host))
```

**example task definition file:**

```yaml
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
- name: source
- name: version

outputs:
- name: configuration

run:
  path: sh
  args:
  - -excu
  - |
    export VERSION=$(cat version/number)
    apk add --no-progress gettext # TODO: create/use an image with this already installed
    envsubst < source/deployment/${FILE} > configuration/${FILE}
    cat configuration/${FILE}
```

**example feeding the output into this resource:**

```yaml
  - put: kubernetes-development
    params:
      kubectl: apply -f web-k8s-configuration/web.yml
```

**Comment by superbrothers** [comment]
@sanjay2916 I also recommand you to create manifest files and run `kubectl apply` instead of using `kubectl set image`. However you can also use command substitution as follows:

```yaml
jobs:
- name: kubernetes-deployment
  plan:
  - get: nginx-image
  - put: kubernetes-development
    params:
      kubectl: set image deploy/nginx nginx="$(cat nginx-image/repository):$(cat nginx-image/tag)"
```

@lnhrdt Thank you for your comment :+1:
