### ISSUE TITLE
Wishlist: Wait Until Kubernetes Job/Pod Complete

### ISSUE THREAD

**Issue by chrishiestand** [zlabjp/kubernetes-resource#44]
There is a lot of power/utility in this resource by adding native support for waiting for jobs or pods to be complete.

Concourse could be used to kickoff asynchronous kubernetes tasks and the concourse build could fail on kubernetes job failure.

I only have short-lived jobs in mind, more care might be needed to support long-lived jobs.

UPDATE: I realized that for many use cases concourse tasks are equivalent to kubernetes jobs. So I think this is only useful if you want the job to run within the target kubernetes cluster and not from concourse.

**Comment by wernerb** [comment]
There is an experimental kubectl wait command that is more flexible (https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait) that can also be used for jobs or any other resource.

It is still experimental though, so perhaps add an additional parameter where this command can be set which would also disable the wait-until-ready until the wait command is stable
?

**Comment by superbrothers** [comment]
You can disable wait-until-ready by setting `0` to `output.wait_until_ready` as follows:

```yaml
jobs:
- name: kubernetes-deploy-production
  plan:
  - get: my-app
    trigger: true
  - put: kubernetes-production
    params:
      kubectl: apply -f my-app/k8s -f my-app/k8s/production
      wait_until_ready: 0
```

- `wait_until_ready`: Optional. The number of seconds that waits until all pods are ready. 0 means don't wait. Defaults to 30.

Therefore, you can use `kubectl wait` instead of wait-until-ready at this time.

```yaml
jobs:
- name: kubernetes-deploy-production
  plan:
  - get: my-app
    trigger: true
  - put: kubernetes-production
    params:
      kubectl: apply -f my-app/k8s -f my-app/k8s/production
      wait_until_ready: 0
  - put: kubernetes-production
    params:
      kubectl: wait --for condition=Ready -l run=nginx pod
      wait_until_ready: 0
```

Please try it!
