### ISSUE TITLE
Unable to connect with Google Kubernetes engine

### ISSUE THREAD

**Issue by DhingraParul** [zlabjp/kubernetes-resource#53]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- bug

**What happened**:
I am trying to deploy my application to GKE, from concourse pipeline, and after configuring the kubeconfig file and during execution it's giving below error:
```
+ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

Not sure why it is trying to connect with localhost instead of cluster IP address.

**Environment**:
- Concourse CI version: (use `fly --version`):v3.14.1
- kubernetes-resource image version:1.12

Below is the snippet from pipeline.yaml file:

```resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.12"

resources:


- name: k8s
  type: kubernetes
  source:
    kubeconfig: |
      apiVersion: v1
      clusters:
      - cluster:
          certificate-authority-data: ((cert_auth-data))
      server: https://xx.xx.xx.xx:8080
      name: ((name))
      contexts:
      - context:
          cluster: ((name))
          user: ((name))
        name: ((name))
      current-context: ((name))
      kind: Config
      preferences: {}
      users:
      - name: ((name))
        user:
          client-certificate-data: ((client-certificate-data))
          client-key-data: ((client-key-data))
```

**Comment by superbrothers** [comment]
It seems that kubeconfig data is broken in your pipeline.yml. Could you make the whole `kubeconfig` source configuration a variable?

```yaml
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.12"

resources:
- name: k8s
  type: kubernetes
  source:
    kubeconfig: (( kubeconfig ))
```

**Comment by DhingraParul** [comment]
Thanks @superbrothers , 
I have tried other way, instead of giving kubeconfig, I tried to pass the various params to source tag like server, namespace, token, certificate_authority, and I am able to connect with the cluster end point by installing self signed certificate too.
But somehow now I am not sure what and how should I proceed to deploy the application.
Below is the snippet of job, whereby I am trying to deploy the application to k8s.
```- name: repo-deploy-dev
  serial: true
  plan:
  - get: repo-snapshot
    trigger: true
    passed: [repo-build-dev]
  - put: k8s
    params:
      kubectl:??? ```

Please help me by sharing the expertise !!

**Comment by superbrothers** [comment]
If your manifest files are included in `repo-snapshot` resource, you can apply them as follows:

```yaml
  serial: true
  plan:
  - get: repo-snapshot
    trigger: true
    passed: [repo-build-dev]
  - put: k8s
    params:
      kubectl: apply -f repo-snapshot/deployment.yaml
```

The below is a sample repository of this concourse resource. Please use it for your information.

- https://github.com/zlabjp/concourse-meetup-tokyo-7-demo
