### ISSUE TITLE
minikube certificate

### ISSUE THREAD

**Issue by ClumsyPotato** [zlabjp/kubernetes-resource#61]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- bug

**What happened**:
I tried to use the custom resource to deploy on minikube

**What you expected to happen**:
I just wanted to execute a simple kubectl get pod to see if i can execute kubectl comands

**How to reproduce it (as minimally and precisely as possible)**:
i tried to pass the ca.cert file (and almost any other .cert  .pem and .key file) from .minikube to the parameter certificate_authority but it did not work.
I also added a token to the token field which i got from kubeadm

this did not work so i copied my entire kubeconf file into source
```


resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.13"

resources:
- name: prod
  type: kubernetes
  source:
    kubeconfig: ((kubeconfig))
    # certificate-authority: ((ca-cert))
    # server: https://<minikubeIP>:8443
    # token: <tokken i got got ftom kubeadm >


jobs:
- name: prod-deploy
  plan:
  - put: prod
    params:
      kubectl: get pods

```
my variable file:

`kubeconfig:
 apiVersion: v1
 clusters:
 - cluster:
     certificate-authority: /home/atm/.minikube/ca.crt
     server: https://<minikubehost>:8443
   name: minikube
 contexts:
 - context:
     cluster: minikube
     user: minikube
   name: minikube
 current-context: minikube
 kind: Config
 preferences: {}
 users:
 - name: minikube
   user:
     client-certificate: /home/atm/.minikube/client.crt
     client-key: /home/atm/.minikube/client.key
`

**Anything else we need to know?**:

I also tried to insert ca.crt client.crt and client.key directly into the file but it still did not work

I have no idea what to try anymore. Pls help :( 

**Environment**:
- Concourse CI version: (use `fly --version`): 4.2.1
- kubernetes-resource image version: minikube version: v0.32.0
- Others:
i run concourse inside a docker container
already tried to mount a persistent volume and put all the certs in int
