### ISSUE TITLE
Can I put multiple kubectl commands? Or inject other shell scripts?

### ISSUE THREAD

**Issue by ZozoZoeLi** [zlabjp/kubernetes-resource#85]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- feature

**What happened**:

It looks like when I try to apply multiple kubectl actions with &&, the command after && is ignored by Concourse. 

First of all, is it a bug?

If not, is there a way I can apply multiple kubectl actions within ONE job?

```
resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.15"

resource:
- name: my-kubernetes-resource
  type: kubernetes
  source:
    server: https://my-server
    namespace: my-namespace
    token: my-token    

job:
- name: my-concourse-job
  plan:
  - get: source-code
    resource: source-code
    trigger: true
  - put: kubernetes-stg
    params:
      kubectl: apply -k source-code/kustomize && set image deployment/my-deployment image=alpine:3.6
```

Also, am I allowed to inject shell scripts within this resource? Something may be like

```
job:
- name: my-concourse-job
  plan:
  - get: source-code
    resource: source-code
    trigger: true
  - put: kubernetes-stg
    params:
      kubectl: apply -k source-code/kustomize
    args:
    - -exc
    - | 
       uname -a
```
**Environment**:
- Concourse CI version: (use `fly --version`): 5.6.0
- kubernetes-resource image version: 1.15.0

**Comment by superbrothers** [comment]
> First of all, is it a bug?

It is not a bug. We don't support && using in the `kubectl` param, so you need to separate a single step to multiple steps.

```yaml
  - put: kubernetes-stg
    params:
      kubectl: apply -k source-code/kustomize
  - put: kubernetes-stg
    params:
      kubectl: set image deployment/my-deployment image=alpine:3.6
```
